[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.4.3"
env_logger = "0.11.8"
ethers-signers = "2.0.14"
hyperliquid_rust_sdk = "0.6.0"
log = "0.4.29"
tokio = "1.49.0"
